### ISSUE TITLE
Can't find NDI runtime library

### ISSUE THREAD

**Issue by derrgis** [impsnldavid/jit.ndi#11]
Not directly related to jit.ndi but it seems NDI has changed the location or the name for the runtime download ressources.
the installer for the application that allows you to capture the screen to transmit over NDI to receivers on the network is now called NewTekNDIScanConverter (.pkg) 

Unfortunately after several tries I still get this :

Can't find NDI runtime library - 'dlopen(/usr/local/lib/libndi.4.dylib, 5): image not found'. Please download and/or reinstall NDI runtime from 'http://new.tk/NDIRedistV4Apple' and restart Max

Is there anything we can do here?

Thank you for advising me.

my current setup
mac OS 10.13.6 3,46 GHz 6-Core Intel Xeon 32 Go 1333 MHz DDR3 GPU : ATI Radeon HD 5770 1024 Mo
Max 8.1.8 gl3

**Comment by derrgis** [comment]
I forgot to tell I have no issue on windows 10 with fresh NDI installation + jit.ndi mxe64

**Comment by pixsperdavid** [comment]
https://ndi.tv/tools/

You can download the mac version of the NDI tools (which incudes the runtime) from the above link. It's a shame that NewTek haven't maintained the other link as it's the one which is actually provided by their source code...

**Comment by derrgis** [comment]
Yes thx, done ... but no success after two installations. Indeed, they probably have to many people working on the project ;-)

**Comment by derrgis** [comment]
However there is nothing named runtime in the mac tools

**Comment by pixsperdavid** [comment]
https://ndi.palakis.fr/runtime/ndi-runtime-4.5.1-macOS.pkg

Try the above.

**Comment by derrgis** [comment]
Yes! the download is good, the installation too.
I'm on the RPI side now.
Thx David for your support, you're great :)
