### ISSUE TITLE
NDI / HX support ?

### ISSUE THREAD

**Issue by amyamazing** [impsnldavid/jit.ndi#12]
Hi, 
The stream from the app "NDI HX Camera" is working fine.

But it seems that Max/Msp can't process feeds from "camera with NDI/HX driver". 
https://www.newtek.com/ndihx/products/upgrade/
The name of the feed shows up, but the stream itself is not handled.
Am I correct ?

Thanks

**Comment by pixsperdavid** [comment]
You need to install the NDI|HX driver which is included in the NDI tools package.

**Comment by amyamazing** [comment]
Sorry, but I checked again & reinstalled the NDI|HX driver.

"Newtek NDI Video Monitor" processes the "Camera HX" stream ok, and other softwares like MimoLive process the stream ok too on this computer.
Unfortunately, in Max it is just a black image (in fact no image at all). 

I believe the app "NDI HX Camera" is HX2 and works ok with jit.ndi, but "cameras with NDI/HX driver" is just HX(1) and it's not implemented in jit.ndi. 
http://www.sienna-tv.com/ndi/knowhowhx2.html

**Comment by pixsperdavid** [comment]
Have just tested with the NDI HX Camera app on my iPhone, was able to successfully receive the stream in Max. There is no actual 'implementation' of NDI HX/HX2 as it's entirely opaquely handled by the NDI runtime. As far as the Max object is concerned HX sources are just another NDI source and do not appear any differently.

I will leave this issue closed, however if you're still having issues with not receiving sources, please open a new issue and include your OS, system NDI and Max version numbers.
