### ISSUE TITLE
"Download NewTek NDI Runtime" Link in jit.ndi.receive~ Help File is No Longer Valid

### ISSUE THREAD

**Issue by boomninjavanish** [impsnldavid/jit.ndi#14]
Hi! The link for "Download NewTek NDI Runtime" within the help patcher is no longer valid. I cannot find the standalone runtime [anywhere on their site](https://www.google.com/search?client=safari&rls=en&biw=1280&bih=1335&ei=rQPlX5OODKix5NoPlceM8As&q=site%3Andi.tv+ndi+%22runtime%22&oq=site%3Andi.tv+ndi+%22runtime%22).

**Comment by amyamazing** [comment]
Hi,
You should try the version 4.5.1 on this archive
https://ndi.palakis.fr/runtime/

**Comment by boomninjavanish** [comment]
Hi amyamzing!

Thanks for the link! I just installed the tools linked in the help patcher. I am more worried about potential new users being confused as the tools don't explicitly install anything named "runtime". I know I was.

**Comment by pixsperdavid** [comment]
This link has been checked and does lead to a valid download as of v0.3.0.

**Comment by randallpacker** [comment]
Hi David... Bravo, Jit.NDI now works great!!! Thank you so much I have been waiting for Max integration with NDI. The only issue I have had so far is finding the runtime link. It doesn't work on the help patch but I was able to dig it out of the max console error messages. 

Jit.NDI is particularly exciting with NDI Bridge, with the ability to network Max video and audio over the Internet. 

Best, Randall

**Comment by randallpacker** [comment]
Hi David, I don't know why this runtime is such a mysterious hard to find entity! This time clicking on the link didn't even put an error message in the Max Console as it did on my M1 Mac. I found the libNDI for Mac installer but it doesn't work on my Intel machine. The link in the patch is supposed to output the URL? Where is it?. Can you help me out on this? 

Thanks! Randall
