### ISSUE TITLE
dynamic renaming

### ISSUE THREAD

**Issue by generalh** [impsnldavid/jit.ndi#15]
Dear David,
This a feature request and is it already possible...
Could we get a dynamic renaming attribute after load of the object in a patch?
Thank you
Hubert

**Comment by pixsperdavid** [comment]
Presume you're talking about jit.ndi.send? It's possible, I just didn't implement it to simplify the object code as I didn't feel there was a compelling use case for needing to do this. Can you explain your requirements?

FYI it should also be possible to achieve this by instantiating the object via javascript, which might work better for a dynamic system anyway.

**Comment by generalh** [comment]
Hello David,
I have a 528 I/O SDI grid to route to some ndi flows and it would be useful to rename it with the name of the SDI flow without to have to recreate a jit.ndi.send @name each time.
I thought about having a list in a umenu and just choose the right name. 
Even if you implement it, does it mean it will just modify the name of the flow on the network or will the receiver need to reconnect to the « new named » flow?

I’ll take a look to Javascript, should find something on the forum!

However thanks a lot for sharing your work! 

Best regards

Hubert

**Comment by pixsperdavid** [comment]
There's no concept of renaming in NDI, you can't change the name of a source once created. If I implemented this, all it would do is destroy the internal sender instance and create a new one. Any connected receivers would disconnect, and need to be themselves updated to the new name.

**Comment by generalh** [comment]
Hello David,
I was expecting this behavior . So i’ll run through a dynamic renaming. Thanks for clarifying !
Well it could have been a good idea to add a kind of label independent of the stream id in the ndi protocol…May be later in an smpte 2110 upgrade ;-)

Merci
Hubert
