### ISSUE TITLE
Unable to run: no such object

### ISSUE THREAD

**Issue by randallpacker** [impsnldavid/jit.ndi#19]
<img width="1474" alt="Screen Shot 2021-09-04 at 10 14 02 AM" src="https://user-images.githubusercontent.com/3989315/132097736-8b9004fc-5293-4317-b699-88401403b156.png">
Greetings: I am receiving the error message "No such object" after doing all the steps:

-- NDI package is in the package manager in Max 8
-- installed the runtime located at: http://new.tk/NDIRedistV4Apple
-- installed NDI Tools 5
-- then tried to install another runtime, but the link is broken: https://ndi.palakis.fr/runtime/

I am running the following
-- latest version of Max
-- Mac OS Big Sur (latest version)
-- Apple Silicon Mac Mini

I would really love to use the package as I am working on an online audio-visual performance project. 

Thanks!!!

Randall Packer

**Comment by randallpacker** [comment]
Is anyone paying attention to this github site? I would truly welcome a response. Thanks! Randall

**Comment by pixsperdavid** [comment]
Max is failing to load the object. Check that you've definitely downloaded the release zip(https://github.com/pixsperdavid/jit.ndi/releases/download/v0.2.0/jit.ndi_v0_2_0.zip) rather than the source. code. If you have, then take a look at https://cycling74.com/articles/using-unsigned-max-externals-on-mac-os-10-15-catalina

**Comment by randallpacker** [comment]
Thanks David for the quick response. You were right, I had loaded the source (jit.ndi.master). However, now I have run up against the quarantine issue. I went to the page you suggested, but it refers to Catalina and I am running Big Sur (on an Apple Silicon Mac Mini), and there are about a hundred different suggestions for how to do this. Wouldn't it be simpler if you can provide the workaround and exact terminal message/address given the application is in the package manager? That way I would better trust the procedure. 

Thanks, Randall

**Comment by pixsperdavid** [comment]
I've never had to use this workaround myself so I can't provide any advice or help with it unfortunately. AFAIK this issue will affect any mac OS version from Catalina onwards.

**Comment by randallpacker** [comment]
Thanks David. I need this to be super stable for a production I am working on and though I am sick and tired of SyphonNDI, I'll stick to it for the time being. I am really surprised that Cycling '74 doesn't have in-house externals for NDI I/O. Any chance your Jit.NDI will be incorporated into the Package Manager with support? Best, Randall

**Comment by pixsperdavid** [comment]
That would be a decision for them, I'd be happy to incorporate if requested.

I won't make any guarantees on the object's stability at present, but I would say that the issue you're facing above doesn't really have any bearing on that, it's just a code-signing security restriction, the OS is not allowing Max to load the extension. Once you remove the quarantine flags from the binaries, it should function fine and won't suddenly stop working.
