### ISSUE TITLE
yxml library missing and can't find it 

### ISSUE THREAD

**Issue by gluon** [impsnldavid/jit.ndi#21]
Hi there,
yxml library missing for compilation and doesn't seem to be in requirements list.

Is there something I missed ?

Thanks a lot.

**Comment by gluon** [comment]
ok, files can be found there (for reference purpose) : 
https://dev.yorhel.nl/yxml

**Comment by pixsperdavid** [comment]
yxml is linked as a git submodule. You need to run `git submodule --init --recursive` after cloning.
