### ISSUE TITLE
jit.ndi.send~ XCode compilation succeed, but "cannot find executable for CFBundle ...

### ISSUE THREAD

**Issue by gluon** [impsnldavid/jit.ndi#22]
Hi there,
jit.ndi.send~ XCode compilation succeed, but "cannot find executable for CFBundle ... when loading it in Max.

"jit.ndi.send~: unable to load object bundle executable"
file is in the correct place, compilation succeed.
what could I miss ?!

**Comment by pixsperdavid** [comment]
Closing this as the build system has now changed.
