### ISSUE TITLE
The file name of NDI dylib does no longer have a version number on macOS

### ISSUE THREAD

**Issue by tomoyanonymous** [impsnldavid/jit.ndi#26]
Hi. I tried to use the external but NDI runtime could not be found at first.
The error message on Max console indicated that it requires `/usr/local/lib/libndi.4.dylib` but the actual dylib name was `/usr/local/lib/libndi.dylib`. 
I made a symlink with the command `ln -s /usr/local/lib/libndi.dylib /usr/local/lib/libndi.4.dylib` and it worked. Maybe is it the change since NDI 5?

Macbook Pro 16inch(2019)
macOS 10.15.7
Max 8.1.5
jit.ndi 0.3.0

**Comment by pixsperdavid** [comment]
The library name is defined in the NewTek supplied NDI library header as follows:

https://github.com/pixsper/jit.ndi/blob/a5637d700ead906da06e39266bddd2a8a85b89b9/source/newtek-ndi-sdk/Processing.NDI.Lib.h#L62

If Max is complaining about not being able to find /usr/local/lib/libndi.4.dylib then it's possible it may have already followed a symlink to that file which is now missing?

**Comment by tomoyanonymous** [comment]
Oh, no sorry I was using the version jit.ndi v0.2.0... 
On 0.3.0, the external could not be found at first again, but this time, because the minimum version requirement was Max 8.2.0 and my environment was 8.1.5. I modified that part in package-info.json and it started working. Thank you!

**Comment by pixsperdavid** [comment]
Good to know. Yes the library name in previous NDI versions was different (from v0.2.0):

https://github.com/pixsper/jit.ndi/blob/9275ff8236f6493318aa8214879e621820d14ddf/lib/NewTek%20NDI%20SDK/Include/Processing.NDI.Lib.h#L59
