### ISSUE TITLE
NDI HX3

### ISSUE THREAD

**Issue by randallpacker** [impsnldavid/jit.ndi#27]
There was announcement today of NDI HX3. As I understand it, sounds like it uses much less bandwidth. Any chance that you will be supporting it any time soon? 
https://www.ndi.tv/blog/ndihx3/

Thanks, Randall

**Comment by pixsperdavid** [comment]
HX support for NDI is opaque to the consuming application as it is entirely managed by the NDI runtime, so HX3 should work as soon as NewTek release an NDI runtime which is compatible with it.

**Comment by randallpacker** [comment]
Thanks David. NewTek just announced the new developer's kit. There is information on this page: https://www.ndi.tv/sdk/
Do you know if they are distributing a new runtime for this? And if so, where it could be found?
