### ISSUE TITLE
NDI 5.5

### ISSUE THREAD

**Issue by randallpacker** [impsnldavid/jit.ndi#28]
Greetings. I would like to update to NDI 5.5 and I wanted to know if this could cause any conflicts with Jit.NDI. 

Many thanks!! Randall

**Comment by pixsperdavid** [comment]
jit.ndi dynamically loads whichever NDI runtime is installed so should work fine with 5.5.

If you have any specific problems, please reopen the issue.

**Comment by randallpacker** [comment]
Thanks David!
