### ISSUE TITLE
Can't find the runtime

### ISSUE THREAD

**Issue by troyrollins** [impsnldavid/jit.ndi#29]
Running the latest Max, NDI, and NDI sender on one of my Macs (intel, Monterey). NDI is working in all of my other apps.

But in Max, I get this...
![image](https://user-images.githubusercontent.com/5223209/192169267-15180d09-7317-4d95-8867-743996d6fdba.png)

Is that something I can fix?

**Comment by pixsperdavid** [comment]
Have you actually installed the runtime? Other apps might be using a local rather than the system copy.

**Comment by troyrollins** [comment]
Hi David, thanks for the reply.

Yes, I've run NDIToolsInstaller.pkg which is where I believe the Runtime comes from.

![image](https://user-images.githubusercontent.com/5223209/193309908-808131cd-37e6-4702-bf90-79d6167fc3a8.png)

I don't recall doing any more than that on my other systems. Did I miss something?

**Comment by pixsperdavid** [comment]
Try this http://new.tk/NDIRedistV4Apple

**Comment by troyrollins** [comment]
Works now on this system.

Thanks for your assistance and patience.
