### ISSUE TITLE
Newtek NDI® Runtime Link Expired

### ISSUE THREAD

**Issue by FedFod** [impsnldavid/jit.ndi#31]
Link to the Newtek NDI library is expired, would be nice to have an updated link.

**Comment by luklongman** [comment]
same problem!

**Comment by pixsperdavid** [comment]
This unfortunately is only fixable by NewTek. AFAIK there is no other link.

**Comment by amyamazing** [comment]
unofficial repository
https://ndi.palakis.fr/runtime/

**Comment by luklongman** [comment]
Thanks so much for the help! It works for me now. I had to remove "com.apple.quarantine" attributes from each file in the folder before Max could recognise it.

**Comment by randallpacker** [comment]
Happy to say the latest runtime 5.0.10.1 for the Mac worked for me on an Apple Studio M1 Ultra. Thanks!!!

**Comment by pixsperdavid** [comment]
Updated the link in v0.3.2
