### ISSUE TITLE
Jit.NDI resource usage / impact on fps

### ISSUE THREAD

**Issue by randallpacker** [impsnldavid/jit.ndi#32]
Greetings David:

I have been doing some testing on resource usage with Jit.NDI, particularly with frames per second. 

I have six NDI inputs coming in and the drop in frame rate is about 10% with each stream. On Low Resolution, the drop is about 5%. I am using a Mac Studio Ultra (double processor), so I have just about the fastest Mac going. Before turning on the NDI inputs, I am getting 60fps with several other things going on, including Blackmagic input. With all six NDI feeds, it drops to about 35fps. Still not terrible, but I am trying to keep the frame rate as close to 60fps as possible. The NDI sources are coming in at 1280x720 59.94fps. The low bandwidth converts it to 640x360, which is way to low. 

I did note in the Activity Monitor is there is a negligible increase in CPU, but hardly anything. 

I am wondering if this performance is typical (particularly for my very fast Mac), and if there is anything that can be done to ease the drop in framerate. 

Many thanks in advance. 

Best, Randall

**Comment by pixsperdavid** [comment]
I haven't done extensive performance testing of this library. To get a baseline for what you're trying to achieve, I would suggest that you try using another software package supporting NDI (Resolume for example) and see if you can achieve 60 FPS there. The Max implementation is not necessarily the most efficient but 6 x 60 FPS is quite a considerable load so would be interesting to find out if other applications can handle this.

**Comment by randallpacker** [comment]
I just did a test with VDMX and it is rock solid 60fps with six NDI inputs. Your thoughts? Perhaps there is Max overhead that is impact the resources being used? 

I am going to do another test transcoding the six NDI feeds into six Syphon feeds from VDMX to Max and see what kind of performance I am getting.

**Comment by randallpacker** [comment]
Just did a test transcoding from VDMX NDI to Syphon in Max. Pretty much the same results as running six NDI feeds directly into Max, perhaps a few fps higher using this method, but certainly not worth the trouble running another app.

**Comment by pixsperdavid** [comment]
It would seem that what you're actually running up against is the limitations of Jitter performance unfortunately. One change I would like to make to the object which may improve performance slightly is a direct texture output, but I need to investigate if it's possible to decode NDI direct to VRAM for this to have a significant effect. I will close the issue for now but if you find any patch adjustments that improve performance please feel free the share them,
