### ISSUE TITLE
compiled release or build instructions

### ISSUE THREAD

**Issue by jgastonraoul** [impsnldavid/jit.ndi#5]
Hi,

Is there a working compiled release of your external or some sort of build instructions ?

Regards,

Jérémie

**Comment by pixsperdavid** [comment]
Compiled version 0.1.0 now available.

**Comment by jgastonraoul** [comment]
It works, thanks !
Any solution to have it working without manually installing ndi library ? (I'm thinking about standalones).

**Comment by pixsperdavid** [comment]
You'd have to make an installer for your standalone which also installed the NDI runtime. It is possible to implement the NDI library as a local dependency, but I've chosen to use the system-wide dependency as it means I don't have to update the external every time there is a new version of the runtime.
