### ISSUE TITLE
jit.ndi.receive~ not recognised in Max

### ISSUE THREAD

**Issue by 3kta** [impsnldavid/jit.ndi#6]
When I start Max I get the following message:
"Unable to load NDI runtime library. Please download and/or reinstall NDI runtime from 'http://new.tk/NDIRedistV4Apple' and restart Max"
I already installed the runtime, restarted max but the message persists.
Max 8.1.0
MacOS 10.14.6
Any one had the same problem or knows how can I solve it?

**Comment by pascalchampagne** [comment]
Same problem Here, I got it working like a charm on my MacBook that runs on  Catalina 10.15.4 but failed to install it on my Imac that has Mojave. Any clue what is the origin of that problem and what we can do to solve it other than to delete all traces of previous NDI installation ?. 

I will try to update to Catalina if it works once updated. 

By the way, thank you for making this happens !!! @impsnldavid This is amazing work...

**Comment by pixsperdavid** [comment]
Hmm so seems like common thread is that the affected systems are pre-Catalina. I'll try making a build with Mojave and post that for testing.

**Comment by pascalchampagne** [comment]
Go it working as soon as I uptaded my Imac to Catalina and It was just a regular update, not a clean install.

**Comment by shimladnb** [comment]
I'm experiencing the same OSX 10.14.6 Mojave

**Comment by ramagottfried** [comment]
same problem here running Mojave -- I also cloned and built jit.ndi.send with Xcode 11.2, the object builds fine with no error, but I still get the same error message even after installing several times, also tried restarting the computer. 

I was able to download and run one of the examples from the NDI SDK so I think the runtime is correctly installed.

**Comment by pixsperdavid** [comment]
So there's clearly something about the builds I'm making (using Catalina) that stops them from working on Mojave. Would be interested to try a build made using Mojave but I don't actually have a Mac with it installed any more, could anyone help me here?

**Comment by ramagottfried** [comment]
sure, here is the .mxo I built last night does it work on your system?
[jit.ndi.send~.mxo.zip](https://github.com/impsnldavid/jit.ndi/files/4622277/jit.ndi.send.mxo.zip)

**Comment by ramagottfried** [comment]
p.s. I noticed there is no linking to the dynamic library, but assume that somehow the runtime deals with that? (i haven't done any research on it)

**Comment by pixsperdavid** [comment]
The dylib is loaded entirely at runtime, this keeps the external totally independent of the NDI library and means that I don't have to rebuild the external for every runtime change.

**Comment by ramagottfried** [comment]
curious, are you able to instantiate the object I posted earlier on your system in max without an error message?

**Comment by pixsperdavid** [comment]
Yup that works for me on Catalina. Will have a dig through the build settings...

**Comment by pixsperdavid** [comment]
Have a potential fix in v0.1.1 (now on releases page). Please try this and let me know.

**Comment by ramagottfried** [comment]
great, yes working on mojave here

**Comment by Molotovinski** [comment]
I found a runtime: [ndi-runtime-5.0.10.1-macOS.pkg](https://ndi.palakis.fr/runtime/ndi-runtime-5.0.10.1-macOS.pkg)
